config/routes.rb
Rails.application.routes.draw do
  resources :travel_operators

  resources :t_groups

  resources :assistance_fare_groups

  resources :services

  resources :hotels

  resources :countries

  resources :destinations

  resources :aptour_destinations

  get 'operators/:id/providers', :controller => 'operators', :action => 'providers'

  resources :operators

  root 'countries#index'

end

app/models/assistance_fare_group.rb
class AssistanceFareGroup < ActiveRecord::Base
end

app/controllers/assistance_fare_groups_controller.rb
class AssistanceFareGroupsController < ApplicationController
  before_action :set_assistance_fare_group, only: [:show, :edit, :update, :destroy]

  # GET /assistance_fare_groups
  # GET /assistance_fare_groups.json
  def index
    @models = AssistanceFareGroup.order("name").page(params[:page]).per(50)
  end

  # GET /assistance_fare_groups/1
  # GET /assistance_fare_groups/1.json
  def show
  end

  # GET /assistance_fare_groups/new
  def new
    @assistance_fare_group = AssistanceFareGroup.new
  end

  # GET /assistance_fare_groups/1/edit
  def edit
  end

  # POST /assistance_fare_groups
  # POST /assistance_fare_groups.json
  def create
    @assistance_fare_group = AssistanceFareGroup.new(assistance_fare_group_params)

    respond_to do |format|
      if @assistance_fare_group.save
        format.html { redirect_to @assistance_fare_group, notice: 'Assistance fare group was successfully created.' }
        format.json { render :show, status: :created, location: @assistance_fare_group }
      else
        format.html { render :new }
        format.json { render json: @assistance_fare_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistance_fare_groups/1
  # PATCH/PUT /assistance_fare_groups/1.json
  def update
    model = @assistance_fare_group
    respond_to do |format|
      if model.update(assistance_fare_group_params)
        format.html { redirect_to model, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: model }
        format.js   { render js: '$.notify(" Listo '+model.name+'", "success");'}
      else
        format.html { render :edit }
        format.json { render json: model.errors, status: :unprocessable_entity }
        format.js   { render js: '$.notify("Error");'}
      end
    end
  end

  # DELETE /assistance_fare_groups/1
  # DELETE /assistance_fare_groups/1.json
  def destroy
    @assistance_fare_group.destroy
    respond_to do |format|
      format.html { redirect_to assistance_fare_groups_url, notice: 'Assistance fare group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistance_fare_group
      @assistance_fare_group = AssistanceFareGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assistance_fare_group_params
      params.require(:assistance_fare_group).permit(:name, :provider_aptour_id, :operator_aptour_id)
    end
end

app/helpers/assistance_fare_groups_helper.rb
module AssistanceFareGroupsHelper
end

app/views/assistance_fare_groups/_assistance_fare_group.html.erb
<% model = assistance_fare_group %>
<%= form_for(model, remote: true) do |f| %>
<tr>
    <td>
	    <div class="field">
	   		<%= f.text_field :name,:class => "name" %>
	  	</div>
  	</td>
    <td>
		<div class="field">
			<%= f.hidden_field :operator_aptour_id, {:id => "model"+model.id.to_s,:class => "aptour_select2 " }%>
		</div>
    </td>
    <td>
		<div class="field">
			<%= f.select(:provider_aptour_id,{},{}, {:id => "model"+model.id.to_s+"provider",:class => "form-control" })%>
			<%= hidden_field "model"+model.id.to_s+"provider_default","", :value => (model.provider_aptour_id.to_s unless model.provider_aptour_id.nil?) %>

		</div>
    </td>
	<td >
		<div class="actions">
		<%= f.submit "Guardar", class: "btn btn-primary btn-sm" %>
		</div>
	</td>
</tr>
<% end %>

app/views/assistance_fare_groups/_form.html.erb
<%= simple_form_for(@assistance_fare_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :provider_aptour_id %>
    <%= f.input :operator_aptour_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assistance_fare_groups/edit.html.erb
<h1>Editing assistance_fare_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @assistance_fare_group %> |
<%= link_to 'Back', assistance_fare_groups_path %>

app/views/assistance_fare_groups/index.html.erb
<h1>Asistencia</h1>
<%= paginate @models %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Operator aptour</th>
      <th>Provider aptour</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
      <%= render @models %>
  </tbody>
</table>
<%= paginate @models %>
<br>

app/views/assistance_fare_groups/new.html.erb
<h1>New assistance_fare_group</h1>

<%= render 'form' %>

<%= link_to 'Back', assistance_fare_groups_path %>

app/views/assistance_fare_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assistance_fare_group.name %>
</p>

<p>
  <strong>Provider aptour:</strong>
  <%= @assistance_fare_group.provider_aptour_id %>
</p>

<p>
  <strong>Operator aptour:</strong>
  <%= @assistance_fare_group.operator_aptour_id %>
</p>

<%= link_to 'Edit', edit_assistance_fare_group_path(@assistance_fare_group) %> |
<%= link_to 'Back', assistance_fare_groups_path %>