config/routes.rb
Rails.application.routes.draw do
  resources :travel_operators

  resources :t_groups

  resources :assistance_fare_groups

  resources :services

  resources :hotels

  resources :countries

  resources :destinations

  resources :aptour_destinations

  get 'operators/:id/providers', :controller => 'operators', :action => 'providers'

  resources :operators

  root 'countries#index'

end

app/views/aplication/_head.html.erb
<%= content_tag :title, "Colox" %>
<%= stylesheet_link_tag "application", media: :all %>
<%#= javascript_include_tag "application" %>
<%= favicon_link_tag %>
<%= csrf_meta_tags %>

app/views/aplication/_navbar.html.erb
<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand">Colox <i class="fa fa-reddit-square"></i></a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to "Destinos Aptour", countries_path%>
        </li>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Aptour - destinos <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Operadores", travel_operators_path%></li>
              <li><%= link_to "Servicios", services_path%></li>
              <li><%= link_to "Hoteles", hotels_path%></li>
              <li><%= link_to "Aereos", t_groups_path%></li>
              <li><%= link_to "Asistencia", assistance_fare_groups_path%></li>
            </ul>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Aptour - Operador Prestador <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">

              <li><a href="http://10.0.0.230" target="_blank" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Aero web</a></li>

              <li><a href="http://10.0.0.230/abm_aerotours/index" target="_blank" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Aero Geografia</a></li>
              <li><a href="http://10.0.0.230/abm_aerotours/index_hotels" target="_blank" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Aero Cotizador</a></li>
            </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>