config/routes.rb
Rails.application.routes.draw do
  resources :travel_operators

  resources :t_groups

  resources :assistance_fare_groups

  resources :services

  resources :hotels

  resources :countries

  resources :destinations

  resources :aptour_destinations

  get 'operators/:id/providers', :controller => 'operators', :action => 'providers'

  resources :operators

  root 'countries#index'

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.order("name").page(params[:page]).per(50)
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
        format.js   { render js: '$.notify(" Listo '+@country.name+'", "success");'}
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
        format.js   { render js: '$.notify("Error");'}
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :destination_aptour_id)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_country.html.erb
<%= form_for(country, remote: true) do |f| %>
<tr>
    <td>
	    <div class="field">
	   		<%= f.text_field :name %>
	  	</div>
  	</td>
    <td>
		<div class="field">
			<%= f.hidden_field :destination_aptour_id, {:class => "aptour_destinations_select2 span12" }%>
		</div>
    </td>
	<td>
		<div class="actions">
		<%= f.submit "Guardar", class: "btn btn-primary" %>
		</div>
	<td>
</tr>
<% end %>
	

app/views/countries/_form.html.erb
<%= bootstrap_form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%= f.label "Destination Aptour" %><br>
  <%= f.hidden_field :destination_aptour_id, {:id => "aptour_destinations_select2", :class => "span6" }%>
  <br></br>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :destination_aptour_id %><br>
    <%= f.number_field :destination_aptour_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>
<input style="width: 200px;" type="hidden" id="foo" name="foo" />

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Lista Paises</h1>
<%= link_to 'New Country', new_country_path %>
<%= paginate @countries %>

<table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th>Destination aptour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @countries %>
  </tbody>
</table>
<%= paginate @countries %>

<br>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Destination aptour:</strong>
  <%= @country.destination_aptour_id %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>