config/routes.rb
Rails.application.routes.draw do
  resources :travel_operators

  resources :t_groups

  resources :assistance_fare_groups

  resources :services

  resources :hotels

  resources :countries

  resources :destinations

  resources :aptour_destinations

  get 'operators/:id/providers', :controller => 'operators', :action => 'providers'

  resources :operators

  root 'countries#index'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  
  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :destination_aptour_id)
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_destination.html.erb
<tr>
    <td><%= destination.name %></td>
    <td><%= destination.destination_aptour_id %></td>
    <td><%= link_to 'Show', destination %></td>
    <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
    <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :destination_aptour_id %><br>
    <%= f.number_field :destination_aptour_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<script>
$( document ).ready(function() {

  $("#aptour_destinations_select2").select2({
      placeholder: "Buscar",
      minimumInputLength: 2,
      ajax: {
          url: "/aptour_destinations.json",
          dataType: 'json',
          quietMillis: 250,
          data: function (term, page) {
              return {
                  q: term,
              };
          },
          results: function (data, page) {
            return {
                    results: $.map(data, function (item) {
                        return {
                            text: item.nom_des,
                            id: item.id_des
                        }
                    })
                    };
          },
          cache: true
      },
      initSelection: function(element, callback) {
      var id = $(element).val();
        if (id !== "") {
            $.ajax("/aptour_destinations/"+id+".json" , {
                dataType: "json"
            }).done(function(data) {
                                    callback({
                                      text: data.nom_des,
                                      id: data.id_des
                                    }); });
        }
      },
      formatResult: FormatResult, // omitted for brevity, see the source of this page
      formatSelection: FormatSelectionOpe,  // omitted for brevity, see the source of this page
      dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
      escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results
  });

  function FormatResult(item) {
              return item.text;
  }

  function FormatSelectionOpe(item) {
              return item.text;
  }

});
</script>

<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Lista Destinos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Destination aptour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
          <%= render @destinations %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination.name %>
</p>

<p>
  <strong>Destination aptour:</strong>
  <%= @destination.destination_aptour_id %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>